### ISSUE TITLE
Can't select Linebreak with regexp

### ISSUE THREAD

**Issue by AgamlaRage** [zokugun/vscode-explicit-folding#8]
Hello,

first of all thank you so much for your extension.
I feel like I was waiting **one line code folding** since decades!

I'm trying to creates regexp for **SCSS** files.
But it looks like I can't select the **linebreaks** characters.

### Regexp that is working and tested with [Regexr](https://regexr.com/).
```javascript
    // settings.json
    "scss": [
      {
        "beginRegex": " {",
        "endRegex": "[\n| ]}",
         // "endRegex": "/[\n| ]}/g", // I also tryied this, but not working
      },
    ],
```

### Explanation
- `[\n| ]` get either linebreak or space
- `}` get closing brace

### Test code
```scss
#nav-menu-container {
  min-height: calc(100vh + 1px);
  padding-top: calc(#{$spacing} + #{$navbar-height});
  @include mbu(tablet) {
    padding: 10%;
    padding-top: calc(10% + #{$navbar-height});
    display: flex;
    align-items: center;
  }
}
```

With this I'm able to fold the nested block in 1 line, but not the parent element.
I think my regexp is all good except the **linebreak** part.

Could someone help me please ?

Thx
